import React, { Component } from "react"

export const LAYOUT_NAMES = [
  'Image only',
  'Button + image',
  'Click-to-text button',
];

export const SWATCHES = [
  'rgba(255, 255, 255, 1)',
  'rgba(0, 0, 0, 1)',
  'rgba(244, 67, 54, 1)',
  'rgba(233, 30, 99, 1)',
  'rgba(156, 39, 176, 1)',
  'rgba(103, 58, 183, 1)',
  'rgba(63, 81, 181, 1)',
  'rgba(33, 150, 243, 1)',
  'rgba(3, 169, 244, 1)',
  'rgba(0, 188, 212, 1)',
  'rgba(0, 150, 136, 1)',
  'rgba(76, 175, 80, 1)',
  'rgba(139, 195, 74, 1)',
  'rgba(205, 220, 57, 1)',
  'rgba(255, 235, 59, 1)',
  'rgba(255, 193, 7, 1)'
]

export const SHADOWS = [
  {shadow:'0px 16px 64px rgba(0,0,0,0.08)', class:''},
  {shadow:'0px 0px 0px rgba(0,0,0,0.0)', class:'no-shadow'},
  {shadow:'0px 10px 30px rgba(0,0,0,0.08)', class:''},
  {shadow:'0px 5px 10px rgba(0,0,0,0.08)', class:''},
  {shadow:'0px 5px 20px rgba(0,0,0,0.2)', class:''},
  {shadow:'0px 2px 5px rgba(0,0,0,0.8)', class:''},
]

export const CLOSE_POSITIONS = [
  {label:'top-left', value:'cta-close-tl'},
  {label:'top-right', value:'cta-close-tr'},
]

export const BEHAVIOR_POSITIONS = [
  {label:'bottom-right', value:'cta-position-br'},
  {label:'bottom-center', value:'cta-position-bc'},
  {label:'bottom-left', value:'cta-position-bl'},
]

export const BUTTONS_TYPES = [
  {label:'Text only', value:'cta-label-textonly', icon:<i className="icon-text-only"></i>},
  {label:'Text +  icon left', value:'cta-label-texticonl', icon:<i className="icon-text-icon-left"></i>},
  {label:'Text +  icon right', value:'cta-label-texticonr', icon:<i className="icon-text-icon-right"></i>},
]

export const PICKR_CONFIG = {
  COMPONENTS: {
    preview: true,
    opacity: true,
    hue: true,
  
    interaction: {
      input: true,
      clear: true,
      save: true
    }
  },
  THEME: "monolith",
  SAVE: {save: 'Save'}
}

export const ICON_PACK = [
  "pack-type",
  "pack-umbrella",
  "pack-underline",
  "pack-unlock",
  "pack-upload",
  "pack-upload-cloud",
  "pack-user",
  "pack-user-check",
  "pack-user-minus",
  "pack-user-plus",
  "pack-users",
  "pack-user-x",
  "pack-video",
  "pack-video-off",
  "pack-voicemail",
  "pack-volume",
  "pack-volume-1",
  "pack-volume-2",
  "pack-volume-x",
  "pack-watch",
  "pack-wifi",
  "pack-wifi-off",
  "pack-wind",
  "pack-x",
  "pack-x-circle",
  "pack-x-square",
  "pack-youtube",
  "pack-zap",
  "pack-zap-off",
  "pack-zoom-in",
  "pack-zoom-out",
  "pack-activity",
  "pack-airplay",
  "pack-alert-circle",
  "pack-alert-octagon",
  "pack-alert-triangle",
  "pack-align-center",
  "pack-align-justify",
  "pack-align-left",
  "pack-align-right",
  "pack-anchor",
  "pack-announcement-speaker",
  "pack-aperture",
  "pack-archive",
  "pack-arrow-down",
  "pack-arrow-down-circle",
  "pack-arrow-down-left",
  "pack-arrow-down-right",
  "pack-arrow-left",
  "pack-arrow-left-circle",
  "pack-arrow-right",
  "pack-arrow-right-circle",
  "pack-arrow-up",
  "pack-arrow-up-circle",
  "pack-arrow-up-left",
  "pack-arrow-up-right",
  "pack-at-sign",
  "pack-award",
  "pack-bar-chart",
  "pack-bar-chart-2",
  "pack-battery",
  "pack-battery-charging",
  "pack-bell",
  "pack-bell-off",
  "pack-bluetooth",
  "pack-bold",
  "pack-book",
  "pack-bookmark",
  "pack-book-open",
  "pack-box",
  "pack-briefcase",
  "pack-calendar",
  "pack-camera",
  "pack-camera-off",
  "pack-carret---down",
  "pack-carret---left",
  "pack-carret---right",
  "pack-carret---up",
  "pack-cast",
  "pack-check",
  "pack-check-circle",
  "pack-check-square",
  "pack-chevron-down",
  "pack-chevron-left",
  "pack-chevron-right",
  "pack-chevrons-down",
  "pack-chevrons-left",
  "pack-chevrons-right",
  "pack-chevrons-up",
  "pack-chevron-up",
  "pack-chrome",
  "pack-circle",
  "pack-clipboard",
  "pack-clock",
  "pack-cloud-drizzle",
  "pack-cloud-lightning",
  "pack-cloud-off",
  "pack-cloud-rain",
  "pack-cloud-snow",
  "pack-code",
  "pack-codepen",
  "pack-command",
  "pack-compass",
  "pack-copy",
  "pack-corner-down-left",
  "pack-corner-down-right",
  "pack-corner-left-down",
  "pack-corner-left-up",
  "pack-corner-right-down",
  "pack-corner-right-up",
  "pack-corner-up-left",
  "pack-corner-up-right",
  "pack-cpu",
  "pack-credit-card",
  "pack-crop",
  "pack-crosshair",
  "pack-database",
  "pack-delete",
  "pack-disc",
  "pack-dollar-sign",
  "pack-download",
  "pack-download-cloud",
  "pack-droplet",
  "pack-edit",
  "pack-edit-2",
  "pack-edit-3",
  "pack-external-link",
  "pack-eye",
  "pack-eye-off",
  "pack-facebook",
  "pack-fast-forward",
  "pack-feather",
  "pack-file",
  "pack-file-minus",
  "pack-file-plus",
  "pack-file-text",
  "pack-film",
  "pack-filter",
  "pack-flag",
  "pack-folder",
  "pack-folder-minus",
  "pack-folder-plus",
  "pack-gift",
  "pack-git-branch",
  "pack-git-commit",
  "pack-github",
  "pack-gitlab",
  "pack-git-merge",
  "pack-git-pull-request",
  "pack-globe",
  "pack-grid",
  "pack-hard-drive",
  "pack-hash",
  "pack-headphones",
  "pack-heart",
  "pack-help-circle",
  "pack-home",
  "pack-image",
  "pack-inbox",
  "pack-info",
  "pack-instagram",
  "pack-intercom-icon",
  "pack-italic",
  "pack-layers",
  "pack-layout",
  "pack-life-buoy-help",
  "pack-link",
  "pack-link-2",
  "pack-linkedin",
  "pack-list",
  "pack-live-support-agent-headset",
  "pack-loader",
  "pack-lock",
  "pack-log-in",
  "pack-log-out",
  "pack-mail",
  "pack-map",
  "pack-map-pin",
  "pack-maximize",
  "pack-maximize-2",
  "pack-menu",
  "pack-message-circle",
  "pack-message-square",
  "pack-mic",
  "pack-mic-off",
  "pack-minimize",
  "pack-minimize-2",
  "pack-minus",
  "pack-minus-circle",
  "pack-minus-square",
  "pack-monitor",
  "pack-moon",
  "pack-more-horizontal",
  "pack-more-vertical",
  "pack-move",
  "pack-music",
  "pack-navigation",
  "pack-navigation-2",
  "pack-octagon",
  "pack-package",
  "pack-paperclip",
  "pack-pause",
  "pack-pause-circle",
  "pack-percent",
  "pack-phone-chat-message-sms",
  "pack-phone-call",
  "pack-phone-forwarded",
  "pack-phone-incoming-2",
  "pack-phone-missed",
  "pack-phone-off",
  "pack-phone-outgoing",
  "pack-pie-chart",
  "pack-play",
  "pack-play-circle",
  "pack-plug",
  "pack-plus",
  "pack-plus-circle",
  "pack-plus-square",
  "pack-pocket",
  "pack-power",
  "pack-printer",
  "pack-radio",
  "pack-refresh-ccw",
  "pack-refresh-cw",
  "pack-repeat",
  "pack-rewind",
  "pack-rotate-ccw",
  "pack-rotate-cw",
  "pack-rss",
  "pack-save",
  "pack-scissors",
  "pack-search",
  "pack-send",
  "pack-server",
  "pack-settings",
  "pack-share",
  "pack-share-2",
  "pack-shield",
  "pack-shield-off",
  "pack-shopping-bag",
  "pack-shopping-cart",
  "pack-shuffle",
  "pack-sidebar",
  "pack-skip-back",
  "pack-skip-forward",
  "pack-slack",
  "pack-slash",
  "pack-sliders",
  "pack-smartphone",
  "pack-speaker",
  "pack-square",
  "pack-star",
  "pack-stop-circle",
  "pack-sun",
  "pack-sunrise",
  "pack-sunset",
  "pack-tablet",
  "pack-tag",
  "pack-target",
  "pack-terminal",
  "pack-thermometer",
  "pack-thumbs-down",
  "pack-thumbs-up",
  "pack-toggle-left",
  "pack-toggle-right",
  "pack-trash",
  "pack-trash-2",
  "pack-trending-down",
  "pack-trending-up",
  "pack-triangle",
  "pack-truck",
  "pack-tv",
  "pack-twitter"
]